version: '3.8'

services:
  imagimaps-discord-bot:
    build:
      context: .
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    volumes:
      - ./logs:/var/logs/imagimaps_discord_bot
